# This file was generated by GoReleaser. DO NOT EDIT.
cask "vedi" do
  version "1.12.0"

  on_macos do
    on_arm do
      sha256 "972641d5cd5705886df05d3affbe380381f700ea3bef798b8f0c1d8c57ba21c0"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3fe5d626983ebe18bff9582260c983ed230f37348db78fcee56ae1985a96721"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c941371936b1ea0e441b74505b4e3bfe12e20f3fedb44e5125648209ecfbf93"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd879fea3f9e2919ea9679dd3740b66b8b406bae88be8b638907d35919c7a0fb"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vedi"
  desc "Pager for colored text; select with the keyboard and copy"
  homepage "https://github.com/dlh/vedi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vedi"
  bash_completion "completions/vedi.bash"
  fish_completion "completions/vedi.fish"
  zsh_completion "completions/_vedi"

  # No zap stanza required
end
