# This file was generated by GoReleaser. DO NOT EDIT.
cask "vedi" do
  version "1.10.0"

  on_macos do
    on_arm do
      sha256 "ecc13a53fc1381d67d7a10000e3c021e9332e9529070e272ea409325688ab42b"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "22b68101af98ca39f87016a07c688d1b13110c68fb34ce663905365788e1a2a3"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d3598b88d4bc086ccd2b49eb85c80a1b1716bd5a90808ccfa8abdd35f464d1d7"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd9cb712a412275b21c950199696833d3509b7ee6c4450fd306fce20cbc58f61"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vedi"
  desc "Pager for colored text; select with the keyboard and copy"
  homepage "https://github.com/dlh/vedi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vedi"
  bash_completion "completions/vedi.bash"
  fish_completion "completions/vedi.fish"
  zsh_completion "completions/_vedi"

  # No zap stanza required
end
