# This file was generated by GoReleaser. DO NOT EDIT.
cask "vedi" do
  version "1.11.0"

  on_macos do
    on_arm do
      sha256 "c61a3192a24e1da99d0f1db5f68072b0940b11fdc2638e730d1dbd320dbf4977"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1333220c75f6338139ad6b6dab61be402f9e0bd15f70b87281945b9c82997fb5"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8697c087e6f0d3d8dfab5bc530f8c8fc12a0b563af01280c730e057982083777"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c3cdda879e3d0998e35784ba964ac928f9a2ecfb284bf6090813a8d5a660820"
      url "https://github.com/dlh/vedi/releases/download/v#{version}/vedi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vedi"
  desc "Pager for colored text; select with the keyboard and copy"
  homepage "https://github.com/dlh/vedi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vedi"
  bash_completion "completions/vedi.bash"
  fish_completion "completions/vedi.fish"
  zsh_completion "completions/_vedi"

  # No zap stanza required
end
